name: overcast
publish_to: 'none'
description: Overcast LAN cloud storage client.
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  file_picker: ^10.3.3
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  video_player: ^2.10.0
  audioplayers: ^6.5.0
  path_provider: ^2.1.5
  mime: ^2.0.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
